spring:
  application:
    name: authservice

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000} # 기본 1시간
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:2592000000} # 기본 30일

server:
  port: 8081

